name: FlowSmith 自律実行依頼
description: FlowSmith 自律開発を実行するための Issue テンプレート（agent-task ラベル付与）
title: "[agent-task] "
labels:
  - agent-task
body:
  - type: markdown
    attributes:
      value: |
        このテンプレートで作成した Issue は `agent-task` ラベルにより FlowSmith の自律実行対象になります。
        実装条件をできるだけ具体的に記載してください。

  - type: textarea
    id: objective
    attributes:
      label: 目的
      description: 何を達成したいか
      placeholder: 例）検索結果APIにページネーションを追加し、既存の一覧表示を維持する
    validations:
      required: true

  - type: textarea
    id: non_goals
    attributes:
      label: 非目的
      description: 今回やらないことを明記してください
      placeholder: 例）管理画面UIの刷新は対象外
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ条件
      description: 完了判定のチェックリスト
      placeholder: |
        - [ ] API の `page` / `limit` 指定で期待件数が返る
        - [ ] 既存エンドポイントの互換性を維持する
        - [ ] 既存テストが通る
        - [ ] 必要な新規テストを追加する
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: 制約
      description: 変更可能パス、実行環境、セキュリティ要件など
      placeholder: |
        例）
        - 変更可能: src/api/**, tests/api/**
        - DBスキーマ変更は禁止
        - 外部通信を伴うテストは禁止
    validations:
      required: false

  - type: textarea
    id: verification
    attributes:
      label: 検証項目
      description: 実行してほしい確認コマンドや確認観点
      placeholder: |
        例）
        - npm test
        - npm run lint
        - npm run build
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 補足情報
      description: 参考資料、関連Issue、設計メモなど
      placeholder: 関連Issue: #12
    validations:
      required: false
